import OpenAI from "openai";

import { CreativeBrief } from "../../../types/CreativeBrief";
import { CreativeAsset } from "../../../types/CreativeAsset";

import { composeImagePrompt } from "../../../engines/promptComposer";

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export class OpenAIImageService {

  //------------------------------------------
  // Generate Image
  //------------------------------------------

  async generateImage(
    brief: CreativeBrief,
    productImage: File | null
  ): Promise<CreativeAsset> {

    //------------------------------------------
    // Verify Product Upload
    //------------------------------------------

    console.log("");
    console.log("=====================================");
    console.log("EmmaOS Product Upload");
    console.log("=====================================");

    if (productImage) {

      console.log("Filename:", productImage.name);
      console.log("Type:", productImage.type);
      console.log("Size:", productImage.size, "bytes");

    } else {

      console.log("No product image received.");

    }

    //------------------------------------------
    // Compose Prompt
    //------------------------------------------

    const prompt =
      composeImagePrompt(brief);

    console.log("");
    console.log("=====================================");
    console.log("EmmaOS Prompt");
    console.log("=====================================");
    console.log(prompt);

    //------------------------------------------
    // Temporary Image Generation
    //
    // NOTE:
    // This still uses text generation only.
    // The next milestone replaces this with
    // reference-image generation.
    //------------------------------------------

    const response =
      await client.images.generate({

        model: "gpt-image-1",

        prompt,

        size: "1024x1024",

        quality: "high",

      });

    //------------------------------------------
    // Extract Image
    //------------------------------------------

    const base64 =
      response.data?.[0]?.b64_json;

    if (!base64) {

      throw new Error(
        "OpenAI did not return an image."
      );

    }

    const imageUrl =
      `data:image/png;base64,${base64}`;

    //------------------------------------------
    // Build Asset
    //------------------------------------------

    return {

      id: crypto.randomUUID(),

      name:
        `${brief.strategy} Image`,

      type: "Image",

      strategy:
        brief.strategy,

      platform:
        brief.platform,

      placement:
        brief.placement,

      provider:
        "OpenAI",

      status:
        "Completed",

      url:
        imageUrl,

      thumbnailUrl:
        imageUrl,

      previewUrl:
        imageUrl,

      prompt,

      width: 1024,

      height: 1024,

      duration: 0,

      size: 0,

      createdAt:
        new Date().toISOString(),

      updatedAt:
        new Date().toISOString(),

      favorite: false,

      tags: [],

      notes:
        "Generated by EmmaOS using OpenAI.",

    };

  }

}

export const openAIImageService =
  new OpenAIImageService();