import OpenAI from "openai";

import { CreativeBrief } from "../types/CreativeBrief";
import { CreativeAsset } from "../types/CreativeAsset";

import { composeImagePrompt } from "../engines/promptComposer";

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export class OpenAIImageService {

  //------------------------------------------
  // Generate Image
  //------------------------------------------

  async generateImage(
    brief: CreativeBrief
  ): Promise<CreativeAsset> {

    //------------------------------------------
    // Compose Prompt
    //------------------------------------------

    const prompt =
      composeImagePrompt(brief);

    //------------------------------------------
    // Call OpenAI Images API
    //------------------------------------------

    const response =
      await client.images.generate({

        // Recommended production model
        model: "gpt-image-1",

        prompt,

        size: "1024x1024",

        quality: "high",

      });

    //------------------------------------------
    // Extract Image
    //------------------------------------------

    /**
     * NOTE:
     *
     * gpt-image-1 returns base64 image data.
     *
     * For now we'll store it as a data URL.
     *
     * Later we'll upload it to cloud storage
     * (S3, Azure, Cloudflare R2, etc.)
     */

    const base64 =
      response.data?.[0]?.b64_json;

    if (!base64) {

      throw new Error(
        "OpenAI did not return an image."
      );

    }

    const imageUrl =
      `data:image/png;base64,${base64}`;

    //------------------------------------------
    // Creative Asset
    //------------------------------------------

    return {

      id: crypto.randomUUID(),

      name:
        `${brief.strategy} Image`,

      type: "Image",

      strategy:
        brief.strategy,

      platform:
        brief.platform,

      placement:
        brief.placement,

      provider:
        "OpenAI",

      status:
        "Completed",

      url:
        imageUrl,

      thumbnailUrl:
        imageUrl,

      previewUrl:
        imageUrl,

      prompt,

      width: 1024,

      height: 1024,

      duration: 0,

      size: 0,

      createdAt:
        new Date().toISOString(),

      updatedAt:
        new Date().toISOString(),

      favorite: false,

      tags: [],

      notes:
        "Generated by EmmaOS using OpenAI.",

    };

  }

}

export const openAIImageService =
  new OpenAIImageService();