"use client";

import { CampaignStrategy } from "../../types/CampaignStrategy";

interface StrategySelectorProps {
  strategies: CampaignStrategy[];
  selectedStrategy: CampaignStrategy;
  onSelect: (strategy: CampaignStrategy) => void;
}

export default function StrategySelector({
  strategies,
  selectedStrategy,
  onSelect,
}: StrategySelectorProps) {
  return (
    <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">

      <div className="mb-4">

        <h2 className="text-lg font-semibold text-slate-900">
          Marketing Strategies
        </h2>

        <p className="mt-1 text-sm text-slate-500">
          Compare multiple marketing approaches generated by Emma.
        </p>

      </div>

      <div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-6">

        {strategies.map((strategy) => {

          const active =
            strategy.type === selectedStrategy.type;

          return (

            <button
              key={strategy.type}
              type="button"
              onClick={() => onSelect(strategy)}
              className={`rounded-xl border p-4 transition-all duration-200 ${
                active
                  ? "border-blue-600 bg-blue-50 shadow-md"
                  : "border-slate-200 bg-white hover:border-slate-300 hover:bg-slate-50"
              }`}
            >

              <div className="text-3xl">
                {strategy.icon}
              </div>

              <div className="mt-2 font-semibold text-slate-900">
                {strategy.type}
              </div>

              <div className="mt-1 text-xs text-slate-500">
                {strategy.primaryEmotion}
              </div>

            </button>

          );

        })}

      </div>

    </div>
  );
}